### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by svenoo** [CheatBreaker/CheatBreakerAPI#5] opened 2020-01-16 08:35 UTC
As I was looking through the code I saw that a depend called 'CheatBreaker NetHandler' was missing.

**Comment by Baitinq** [comment] 2020-01-16 19:07
lol

**Comment by ShonP40** [comment] 2020-01-17 20:46
Duplicate of #3

**Comment by bchubbs** [comment] 2020-01-17 21:26
Jon said that he will probably end up open-sourcing the NetHandler code at some point, but we don't know when that will be just yet.

**Comment by jhalt** [comment] 2020-01-20 06:59
Duplicate of #3. In addition, this has been clearly articulated at the bottom of the README:
https://github.com/CheatBreaker/CheatBreakerAPI/blob/master/README.md#approval-for-public-release

**Closed as completed by jhalt** 2020-01-20 06:59 UTC
